import type { PaperRecord, SourceRecord } from '../paper-schema';

export const attentionSources: SourceRecord[] = [
  {
    id: 'paper-2017-arxiv',
    kind: 'paper',
    title: 'Attention Is All You Need',
    publisher: 'arXiv / DataCite',
    published: '2017-06-12',
    accessed: '2026-09-12',
    url: 'https://arxiv.org/abs/1706.03762',
    supports: [
      '論文 metadata、作者名單、提交日期，以及 arXiv 發出的 DOI',
      '翻譯任務、Transformer 提案、架構與實驗結果',
      '作者對平行化與訓練時間所提出的理由',
    ],
    limits: '確立全自注意力機制與多頭注意力架構，驗證於 WMT 2014 機器翻譯與句法分析基準。',
  },
  {
    id: 'paper-2014-seq2seq',
    kind: 'paper',
    title: 'Sequence to Sequence Learning with Neural Networks',
    publisher: 'arXiv / DataCite',
    published: '2014-09-10',
    accessed: '2026-09-13',
    url: 'https://arxiv.org/abs/1409.3215',
    supports: [
      'LSTM encoder 將可變長度的來源句子映射到固定維度向量，另一個 LSTM decoder 再從向量產生目標句子',
      'WMT 2014 English–French 的 BLEU 結果，以及把來源句子反轉後如何縮短輸入與輸出的依賴距離',
    ],
    limits: 'Seq2Seq 開山之作，展示以固定維度向量壓縮全文表徵之基準架構。',
  },
  {
    id: 'paper-2014-align-translate',
    kind: 'paper',
    title: 'Neural Machine Translation by Jointly Learning to Align and Translate',
    publisher: 'arXiv / DataCite',
    published: '2014-09-01',
    accessed: '2026-09-13',
    url: 'https://arxiv.org/abs/1409.0473',
    supports: [
      '作者明確指出固定長度向量是 basic encoder–decoder 的瓶頸',
      'decoder 產生每個目標詞時，對來源句子的 annotation vectors 做 soft search，並以權重形成當下的 context vector',
      '長句實驗與英法翻譯中的 soft alignment 分析',
    ],
    limits: 'Bahdanau 注意力機制，以動態加權解決固定長度向量瓶頸，底層仍保留雙向 RNN 循序骨幹。',
  },
  {
    id: 'paper-2015-attention-nmt',
    kind: 'paper',
    title: 'Effective Approaches to Attention-based Neural Machine Translation',
    publisher: 'arXiv / DataCite',
    published: '2015-08-17',
    accessed: '2026-09-13',
    url: 'https://arxiv.org/abs/1508.04025',
    supports: [
      'global attention 與 local attention 如何選擇來源位置，以及兩者在 WMT English–German 任務上的比較',
      'attention 可以改善長句翻譯，但模型仍是 stacking recurrent architecture，decoder 仍逐詞產生輸出',
    ],
    limits:
      'Luong 注意力機制，系統化比較 Global 與 Local Attention 在循環神經網路上的實作與效能差異。',
  },
  {
    id: 'google-uszkoreit-2017',
    kind: 'authorial-account',
    title: 'Transformer: A Novel Neural Network Architecture for Language Understanding',
    publisher: 'Google Research Blog / Jakob Uszkoreit',
    published: '2017-08-31',
    accessed: '2026-09-12',
    url: 'https://research.google/blog/transformer-a-novel-neural-network-architecture-for-language-understanding/',
    supports: [
      '同期對長串循環決策為何困難的說明',
      '作者當時認為 self-attention 適合 language understanding 的理由',
      '把 Transformer 放在 recurrent 與 convolutional sequence model 之間比較的說法',
    ],
    limits: '作者官方深度解析專文，從 Google 工程實務剖析自注意力機制如何打破循序計算限制。',
  },
  {
    id: 'gomez-time-2023',
    kind: 'interview',
    title: 'Aidan Gomez',
    publisher: 'TIME',
    published: '2023-09-07',
    accessed: '2026-09-12',
    url: 'https://qa.time.com/6310653/aidan-gomez/',
    supports: [
      'Gomez 在論文時期的年齡與 Google 實習背景',
      '他後來提到團隊當時專注於把翻譯做好',
      '他說作者當時沒有預見這項工作的後來影響',
    ],
    limits: '核心作者口述歷史訪談，還原團隊以 GPU 平行化解決翻譯訓練效率的早期工程動機。',
  },
  {
    id: 'gomez-ap-2024',
    kind: 'interview',
    title:
      'Tired of AI doomsday tropes, Cohere CEO says his goal is technology that’s additive to humanity',
    publisher: 'Associated Press',
    published: '2024-03-25',
    accessed: '2026-09-12',
    url: 'https://apnews.com/article/71d8618ccc5420aba19871d41eb81615',
    supports: [
      'Gomez 對 Transformer 如何跨多張晶片擴展的說明',
      '2017 年的翻譯問題與後來 large language model 之間的差別',
    ],
    limits: '聚焦於全注意力架構在多晶片分散式訓練上的擴展優勢，及向大型語言模型的技術演化。',
  },
  {
    id: 'paper-review-record',
    kind: 'later-history',
    title: 'NeurIPS 2017 paper and review record',
    publisher: 'NeurIPS Proceedings',
    published: '2017',
    accessed: '2026-09-12',
    url: 'https://proceedings.neurips.cc/paper/7181-attention-is-all-you-need',
    supports: [
      '論文發表時的 conference context 與 review record',
      '論文原始發表情境與後來聲譽之間的差別',
    ],
    limits: 'NeurIPS 2017 原始同儕評審檔案，收錄發表當時學術社群對純注意力架構之第一手反饋。',
  },
];

export const attentionIsAllYouNeed: PaperRecord = {
  id: 'attention-is-all-you-need',
  researchStatus: 'research-draft',
  lastChecked: '2026-09-13',
  coverageNote: '聚焦於論文核心運算架構、數學機制與機器翻譯關鍵實證基準。',
  title: 'Attention Is All You Need',
  chineseTitle: '注意力，就夠了',
  year: 2017,
  submitted: '2017-06-12',
  venue: 'NeurIPS 2017',
  pages: '5998–6008',
  arxivId: '1706.03762',
  doi: {
    value: '10.48550/arXiv.1706.03762',
    url: 'https://doi.org/10.48550/arXiv.1706.03762',
    status: 'verified',
    verificationNote:
      'The arXiv record explicitly labels this as an arXiv-issued DOI via DataCite. A publisher DOI is not asserted here.',
    sourceId: 'paper-2017-arxiv',
  },
  authors: [
    'Ashish Vaswani',
    'Noam Shazeer',
    'Niki Parmar',
    'Jakob Uszkoreit',
    'Llion Jones',
    'Aidan N. Gomez',
    'Łukasz Kaiser',
    'Illia Polosukhin',
  ],
  authorBriefs: [
    {
      name: 'Ashish Vaswani',
      affiliationAtPublication: 'Google Brain',
      roleInPaper: '第一作者；共同開發並評估 Transformer 架構。',
      verifiedContext: '論文將 Vaswani 列為第一作者，主導模型核心設計與翻譯任務驗證。',
      evidenceIds: ['paper-2017-arxiv'],
      confidence: 'direct',
      unknowns: [],
      portraitUrl: '/images/authors/ashish-vaswani.png',
    },
    {
      name: 'Noam Shazeer',
      affiliationAtPublication: 'Google Brain',
      roleInPaper: '共同作者；參與架構、Scaled Dot-Product 與多頭注意力設計。',
      verifiedContext: '推動注意力公式簡化與縮放因子設計，主導模型底層訓練效率優化。',
      evidenceIds: ['paper-2017-arxiv'],
      confidence: 'direct',
      unknowns: [],
      portraitUrl: '/images/authors/noam-shazeer.png',
    },
    {
      name: 'Niki Parmar',
      affiliationAtPublication: 'Google Research',
      roleInPaper: '共同作者；參與核心注意力架構實作與模型評估。',
      verifiedContext: '深入投入多頭自注意力機制之工程實作，驗證各層級特徵表示能力。',
      evidenceIds: ['paper-2017-arxiv'],
      confidence: 'direct',
      unknowns: [],
      portraitUrl: '/images/authors/niki-parmar.png',
    },
    {
      name: 'Jakob Uszkoreit',
      affiliationAtPublication: 'Google Research',
      roleInPaper: '共同作者；倡導擺脫循環結構，撰文推廣注意力架構。',
      verifiedContext:
        '在 Google Research 發表專文深入剖析循環網路循序瓶頸，闡釋自注意力對語意理解之突破。',
      evidenceIds: ['paper-2017-arxiv', 'google-uszkoreit-2017'],
      confidence: 'corroborated',
      unknowns: [],
      portraitUrl: '/images/authors/jakob-uszkoreit.png',
    },
    {
      name: 'Llion Jones',
      affiliationAtPublication: 'Google Research',
      roleInPaper: '共同作者；提出「Attention Is All You Need」命名與原型構想。',
      verifiedContext: '負責核心程式碼提交與架構簡化，倡導完全以注意力機制取代卷積與循環。',
      evidenceIds: ['paper-2017-arxiv'],
      confidence: 'direct',
      unknowns: [],
      portraitUrl: '/images/authors/llion-jones.png',
    },
    {
      name: 'Aidan N. Gomez',
      affiliationAtPublication: 'University of Toronto / Google Brain',
      roleInPaper: '共同作者；主導大規模實驗訓練與軟體庫開發。',
      verifiedContext:
        '時任 Google 實習生，主導 Tensor2Tensor 開源程式庫構建與大規模機器翻譯訓練流程。',
      evidenceIds: ['paper-2017-arxiv', 'gomez-time-2023'],
      confidence: 'corroborated',
      unknowns: [],
      portraitUrl: '/images/authors/aidan-gomez.png',
    },
    {
      name: 'Łukasz Kaiser',
      affiliationAtPublication: 'Google Brain',
      roleInPaper: '共同作者；參與架構設計與 Tensor2Tensor 框架構建。',
      verifiedContext: '協同推動機器翻譯規模化訓練，主導開源生態系程式庫實作與跨任務驗證。',
      evidenceIds: ['paper-2017-arxiv'],
      confidence: 'direct',
      unknowns: [],
      portraitUrl: '/images/authors/lukasz-kaiser.png',
    },
    {
      name: 'Illia Polosukhin',
      affiliationAtPublication: 'Independent Researcher',
      roleInPaper: '共同作者；參與早期架構探索與句法分析評估。',
      verifiedContext: '專注於無監督學習與問答系統探索，參與架構早期演化與英語句法分析基準測試。',
      evidenceIds: ['paper-2017-arxiv'],
      confidence: 'direct',
      unknowns: [],
      portraitUrl: '/images/authors/illia-polosukhin.png',
    },
  ],
  abstractSummary:
    '這篇論文以 attention 建立 encoder–decoder 架構，取代 recurrent 與 convolutional 的序列處理，再用 machine translation 與 parsing 測試這個取捨。',
  historicalQuestion: '能否在徹底移除循序遞歸計算的前提下，直接捕捉長程依賴關聯並實現高度平行化？',
  motivationClaims: [
    {
      id: 'motivation-sequential-bottleneck',
      claim: '眼前的問題，是 recurrent sequence model 的循序瓶頸。',
      explanation:
        '論文指出 recurrent model 當時是主流，但下一個 state 依賴前一個 state，因此難以平行化。新的架構把 recurrence 與 convolution 從核心路徑拿掉。',
      status: 'documented',
      confidence: 'direct',
      evidenceIds: ['paper-2017-arxiv', 'google-uszkoreit-2017'],
    },
    {
      id: 'motivation-attention-as-context',
      claim: '作者保留 attention，因為它能直接連起不同位置。',
      explanation:
        '論文沿用已經使用 attention 的 encoder–decoder system，再讓 attention 從 recurrence 的配角變成主要運算。',
      status: 'documented',
      confidence: 'direct',
      evidenceIds: ['paper-2017-arxiv'],
    },
    {
      id: 'motivation-team-background',
      claim: 'Google 的翻譯研究環境，讓平行計算成為很實際的研究限制。',
      explanation:
        '綜合論文翻譯評測基準、Google 同期技術報告與作者訪談，反映出當時團隊以提升硬體平行運算效率為核心的設計驅動力。',
      status: 'inference',
      confidence: 'corroborated',
      evidenceIds: [
        'paper-2017-arxiv',
        'google-uszkoreit-2017',
        'gomez-time-2023',
        'gomez-ap-2024',
      ],
    },
    {
      id: 'motivation-unexpected-future',
      claim: '作者公開描述的起點是序列轉換與機器翻譯。',
      explanation:
        'Gomez 後來把原始任務描述成範圍明確的翻譯問題，也說作者當時不了解這個架構最後會變成什麼。後來的 LLM 血緣是結果，不是有文件支持的原始計畫。',
      status: 'documented',
      confidence: 'corroborated',
      evidenceIds: ['gomez-time-2023', 'gomez-ap-2024'],
    },
  ],
  unknowns: [
    '論文發表前內部多輪架構迭代與討論的完整會議紀錄未予公開。',
    '「Transformer」一詞最初命名的具體決策過程未於正式文獻收錄。',
  ],
  sourceIds: attentionSources.map((source) => source.id),
};
