export interface DraftSection {
  heading: string;
  body: string;
}

export interface MilestonePaper {
  id: string;
  vol: string;
  year: number;
  date: string;
  title: string;
  chineseTitle: string;
  authors: string;
  org: string;
  venue: string;
  arxivId?: string;
  url: string;
  status: 'published' | 'outline';
  track: 'language' | 'multimodal';
  theme: string;
  kicker: string;
  why: string;
  how: string;
  what: string;
  outline: {
    history: string;
    theory: string;
    flood: string;
  };
  draftSections?: DraftSection[];
}

export const milestonePapers: MilestonePaper[] = [
  // ==================== 序章：資訊的創世紀（前史） ====================
  {
    id: 'a-mathematical-theory-of-communication',
    vol: '00',
    year: 1948,
    date: '1948.07',
    title: 'A Mathematical Theory of Communication',
    chineseTitle: '資訊理論：資訊有了度量，語言成了機率',
    authors: 'Claude E. Shannon',
    org: 'Bell System Technical Laboratories',
    venue: 'Bell System Technical Journal, Vol. 27',
    url: '/papers/a-mathematical-theory-of-communication',
    status: 'published',
    track: 'language',
    theme: '資訊誕生',
    kicker: 'PROLOGUE / THE GENESIS OF INFORMATION',
    why: '你今天傳一封 LINE 訊息，或讓 ChatGPT 幫你寫一段文字，背後都有一個問題沒人回答過：「資訊」到底是什麼？它可以被量化嗎？在 1948 年以前，這個問題只是哲學討論；沒有人能告訴你一條通訊線路能傳多少「意思」，也沒有人能說清楚語言到底有多少不確定性。',
    how: 'Shannon 做了一個非常大膽的切割：他說訊息的「語義」跟工程無關，重要的是「這條訊息是從多少種可能性裡被選出來的」。接著他定義了「資訊熵」——可能性越多、越意外的訊息帶有越多資訊。為了驗證，他直接用英文字母和詞彙的出現機率，手算了不同階數的馬可夫鏈，生成出讀起來愈來愈像英文的隨機文字——人類第一個統計語言生成模型，就這樣在他的論文裡誕生了。',
    what: '這篇論文建立了整個資訊時代的地基。但對 AI 來說，最直接的遺產是：Shannon 定義的「熵」，就是今天所有大型語言模型在訓練時最佳化的目標——「Cross-Entropy Loss（交叉熵損失）」。每次模型預測下一個 token，它試圖最小化的那個數字，正是 Shannon 1948 年寫下的公式。',
    outline: {
      history:
        '1948 年之前，通訊工程師只知道雜訊會干擾訊號，卻無法精確定義「一條線路能承載多少資訊」。Shannon 是怎麼把這個模糊問題變成可計算數學的？',
      theory:
        '資訊熵公式 $H = -\\sum p_i \\log p_i$ 怎麼讀？為什麼「很意外的事情」帶有更多資訊？Shannon 的 0-gram、1-gram、2-gram 英文馬可夫模型長什麼樣子？',
      flood:
        '從 Shannon 手算的幾句隨機英文，到 GPT-4 用千億參數預測下一個 token——兩者之間的核心邏輯是什麼？Cross-Entropy Loss 和 Shannon Entropy 的數學血緣關係。',
    },
    draftSections: [
      {
        heading: '為什麼研究通訊，反而得先丟掉「意義」？',
        body: '這是這篇論文最關鍵的反直覺洞見：直覺上常認為語言的核心在於「語意」，但 Shannon 指出從通訊工程視角，語意無關宏旨，核心在於該訊息在整體狀態空間中被選中的機率。可能性越多、機率越低，所承載的資訊量（不確定性之消除）便越大。這項「抽離語意」的抽象化操作，使語言與通訊得以首度轉化為嚴格的公理化數學。',
      },
      {
        heading: '1948 年的論文裡，藏著現代語言模型的核心邏輯',
        body: '很多人以為語言模型是深度學習時代的產物。但 Shannon 在論文第三節就親手做了：用英文字母的出現機率，生成 0-gram（完全隨機）、1-gram（按字母頻率抽樣）、2-gram（看前一個字母決定下一個）的文字序列。2-gram 生成的結果已經開始有英文的「感覺」了。這就是現代語言模型「根據前文預測下一個 token」的最早原型——不是神經網路，是 Shannon 用機率表手算出來的。',
      },
      {
        heading: 'Shannon Entropy 和 Cross-Entropy Loss：70 年後還是同一條公式',
        body: '今天訓練 GPT 或任何語言模型，都需要一個「損失函數」來衡量模型預測得準不準。這個損失函數叫做 Cross-Entropy Loss，公式就是 Shannon 在 1948 年寫下的熵的變形。訓練的本質，就是讓模型對語言的機率預測，無限逼近人類語言真實的資訊分布。Shannon 的那個數學框架，在七十年後依然是大語言模型每次更新參數的依據。',
      },
    ],
  },
  // ==================== 系列一：語言基石與大模型演進 ====================
  {
    id: 'attention-is-all-you-need',
    vol: '01',
    year: 2017,
    date: '2017.06',
    title: 'Attention Is All You Need',
    chineseTitle: '注意力，就夠了：架構的結構革命',
    authors: 'Ashish Vaswani et al.',
    org: 'Google Brain / Google Research',
    venue: 'NeurIPS 2017',
    arxivId: '1706.03762',
    url: '/papers/attention-is-all-you-need',
    status: 'published',
    track: 'language',
    theme: '架構革命',
    kicker: 'VOL. 01 / THE ARCHITECTURE',
    why: '過去 30 年的循環神經網路（RNN）像玩傳話遊戲，記憶容量受限於固定向量，梯度易消失，且無法利用 GPU 平行計算長句子。',
    how: '徹底拋棄循環（Recurrence）與卷積，以 Self-Attention 機制讓每個 token 能同時且直接與整段文字中的其他位置計算關聯度。',
    what: 'Transformer 架構誕生；刷新英德/英法機器翻譯紀錄，並成為日後所有近代大語言模型（LLM）的共同骨架。',
    outline: {
      history: '從 2014 Seq2Seq 的固定向量瓶頸，到 Bahdanau 的注意力修補，最終決定徹底打破循環鏈。',
      theory: 'Self-Attention 數值運算、Query/Key/Value 三方分工、Softmax 權重分配與多頭機制。',
      flood: '翻譯專用架構如何意外蔓延至整個自然語言處理與生成式人工智慧領域。',
    },
  },
  {
    id: 'improving-language-understanding-by-generative-pre-training',
    vol: '02',
    year: 2018,
    date: '2018.06',
    title: 'Improving Language Understanding by Generative Pre-Training',
    chineseTitle: 'GPT-1：無監督生成式預訓練的黎明',
    authors: 'Alec Radford, Karthik Narasimhan, Tim Salimans, Ilya Sutskever',
    org: 'OpenAI',
    venue: 'OpenAI Preprint',
    url: '/papers/improving-language-understanding-by-generative-pre-training',
    status: 'published',
    track: 'language',
    theme: '預訓練範式',
    kicker: 'VOL. 02 / GENERATIVE PRE-TRAINING',
    why: '監督式學習極度依賴昂貴且有限的人工標註數據，模型換一個任務就必須從頭訓練。',
    how: '只取 Transformer Decoder 架構，在海量無標註書籍文本上執行「預測下一個字」的自回歸預訓練，再於特定任務上做微調。',
    what: '確立了「大數據無監督預訓練 + 小數據微調」的兩階段標準範式，開啟 GPT 家族的演進序列。',
    outline: {
      history: 'Word2Vec 與 ELMo 的啟發：靜態詞向量無法應付動態上下文，預訓練需要更深的模型。',
      theory:
        '自回歸語言模型（Causal Language Modeling）損失函數、Masked Attention 的單向因果遮罩。',
      flood: '微調（Fine-tuning）時代正式拉開序幕，NLP 迎來大規模遷移學習的新浪潮。',
    },
  },
  {
    id: 'bert-pre-training-of-deep-bidirectional-transformers-for-language-understanding',
    vol: '03',
    year: 2018,
    date: '2018.10',
    title: 'BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding',
    chineseTitle: 'BERT：雙向深層理解的巔峰',
    authors: 'Jacob Devlin, Ming-Wei Chang, Kenton Lee, Kristina Toutanova',
    org: 'Google AI Language',
    venue: 'NAACL 2019',
    arxivId: '1810.04805',
    url: '/papers/bert-pre-training-of-deep-bidirectional-transformers-for-language-understanding',
    status: 'published',
    track: 'language',
    theme: '雙向理解',
    kicker: 'VOL. 03 / BIDIRECTIONAL ENCODER',
    why: '單向自回歸模型只能「由左到右」看前文，但閱讀理解與問答等任務本質上需要同時參考前後文。',
    how: '只取 Transformer Encoder，提出「克漏字挖空」（Masked Language Model, MLM）與「下一句預測」（NSP）作為自監督任務。',
    what: '一口氣刷新 11 項 NLP 任務基準紀錄（SQuAD、GLUE 等），引爆 Encoder 雙向預訓練模型的大規模應用。',
    outline: {
      history: '單向語言模型的視野盲點：為什麼理解問題時必須同時看見句尾？',
      theory: 'Masking 機制與自注意力全域視野、雙向上下文融合數學推導。',
      flood: '引發 RoBERTa、ALBERT、DeBERTa 等結構最佳化，主導 NLP 工業落地多年。',
    },
    draftSections: [
      {
        heading: '傳承第二章的未竟之功：單向因果語言模型的視野盲點',
        body: '在第二章中，GPT-1 首次證明了在無標註文本上預訓練 Transformer 的巨大威力。然而，GPT-1 選擇了「單向因果解碼器」（Decoder-only），強制要求第 i 個字只能看見前文。這種設計在生成文字時非常自然，但用在自然語言理解（NLU）上卻留下了嚴重的未竟之功：語言的語意理解本質上是雙向的。例如在「他在河邊的 bank 釣魚」這句話中，要確認 bank 是「河岸」而非「銀行」，關鍵線索往往落在後面的「釣魚」。GPT-1 在讀到 bank 時後文被遮蔽，人為丟失了一半的關鍵語境。',
      },
      {
        heading: '重拾第一章的遺珠：回歸全雙向 Transformer Encoder 與克漏字革命',
        body: '既然因果遮罩是為了防止預測下一個字時「偷看答案」，那麼只要換個任務，就能徹底解放視野！Google AI 的 Jacob Devlin 等人重新召回第一章被 GPT-1 丟棄的「Transformer Encoder」。在 Encoder 中，Self-Attention 允許每個詞同時與全句所有詞自由互動。為了讓雙向模型無法直接抄襲目標詞，BERT 借鑒了英語考試的「克漏字測驗（Cloze test）」：隨機將 15% 的詞挖空成 [MASK]，逼模型利用前後完整的雙向上下文把原詞猜出來。這一改動直接在 SQuAD 問答與 GLUE 等 11 項基準測試上以壓倒性優勢擊潰了 GPT-1。',
      },
      {
        heading: '大分水嶺之後：BERT 巔峰背後的隱形天花板',
        body: 'BERT 解決了 GPT-1 理解不全面的未竟之功，但也為自己築起了一道無法跨越的高牆：因為克漏字訓練只能填補空缺，BERT 完全無法像 GPT-1 一樣流暢自然地進行開放式的多輪對話與長篇生成。這場雙向與單向的世紀交鋒，直接驅使 OpenAI 在第四章推出 15 億參數的 GPT-2，堅定走向單向自回歸與 Scaling Law 的大道。',
      },
    ],
  },
  {
    id: 'language-models-are-unsupervised-multitask-learners',
    vol: '04',
    year: 2019,
    date: '2019.02',
    title: 'Language Models are Unsupervised Multitask Learners',
    chineseTitle: 'GPT-2：非監督多任務學習與提示詞的萌芽',
    authors: 'Alec Radford, Jeffrey Wu, Rewon Child, David Luan, Dario Amodei, Ilya Sutskever',
    org: 'OpenAI',
    venue: 'OpenAI Paper',
    url: '/papers/language-models-are-unsupervised-multitask-learners',
    status: 'published',
    track: 'language',
    theme: '零樣本學習',
    kicker: 'VOL. 04 / ZERO-SHOT TRANSFER',
    why: '每個任務都要收集標註數據來微調模型依然太昂貴，模型能否不經微調就能處理未見過的任務？',
    how: '將模型擴展到 1.5B 參數，爬取高品質網路文字 WebText，並首創以 Prompt（自然語言提示）引導模型進行零樣本（Zero-shot）推理。',
    what: '展示了規模化帶來的跨任務泛化能力，文本生成品質震撼業界，OpenAI 因安全考量首次引發分階段發布爭議。',
    outline: {
      history: '多任務學習的傳統做法與局限：為什麼「語言」本身就是最通用的任務介面？',
      theory: 'Zero-shot Prompting 的統計原理、BPE Tokenizer 改進與殘差連接初始化優化。',
      flood: '模型規模對文本連貫性的質變，開啟了「Prompt 代替微調」的思維轉型。',
    },
  },
  {
    id: 'scaling-laws-for-neural-language-models',
    vol: '05',
    year: 2020,
    date: '2020.01',
    title: 'Scaling Laws for Neural Language Models',
    chineseTitle: '縮放定律：大語言模型的物理規律',
    authors: 'Jared Kaplan, Sam McCandlish, Tom Henighan, Tom B. Brown, Benjamin Chess et al.',
    org: 'OpenAI',
    venue: 'arXiv Preprint',
    arxivId: '2001.08361',
    url: '/papers/scaling-laws-for-neural-language-models',
    status: 'outline',
    track: 'language',
    theme: '物理定律',
    kicker: 'VOL. 05 / THE SCALING LAWS',
    why: '投入百萬甚至千萬美元訓練大模型像在賭博，模型性能的提升究竟是隨機運氣還是可預測的工程？',
    how: '跨越數個數量級系統性測量參數規模（N）、數據集大小（D）與浮點運算量（C），擬合出跨尺度的冪律公式（Power Law）。',
    what: '證實語言模型性能與資源呈精確的冪律關係；確立了只要擴大參數與算力就能穩定降低損失，給予業界推進千億參數的巨大信心。',
    outline: {
      history: '從試誤經驗到理論規律：深度學習需要一張算力與效果的導航地圖。',
      theory: '冪律公式 $L(N, D, C)$、過擬合邊界、參數與數據分配比例推導。',
      flood: '為 GPT-3 與後續超大模型奠定理論與投資底氣，算力競爭全面爆發。',
    },
  },
  {
    id: 'language-models-are-few-shot-learners',
    vol: '06',
    year: 2020,
    date: '2020.05',
    title: 'Language Models are Few-Shot Learners',
    chineseTitle: 'GPT-3：少樣本學習與湧現能力的爆發',
    authors: 'Tom B. Brown, Benjamin Mann, Nick Ryder, Melanie Subbiah, Jared Kaplan et al.',
    org: 'OpenAI',
    venue: 'NeurIPS 2020',
    arxivId: '2005.14165',
    url: '/papers/language-models-are-few-shot-learners',
    status: 'outline',
    track: 'language',
    theme: '少樣本湧現',
    kicker: 'VOL. 06 / FEW-SHOT & EMERGENT',
    why: '人類學習新技能只需要兩三個範例，機器是否也能在「完全不更新權重」的前提下即學即用？',
    how: '將參數推向 175B 的前所未有規模，在提示詞中直接給出範例進行 In-Context Learning（上下文學習）。',
    what: '展現出寫程式、翻譯、常識推理等多領域的強大湧現能力，正式敲開現代生成式 AI 工業的商業化大門。',
    outline: {
      history: 'In-Context Learning 是如何發生的？從微調到無梯度少樣本提示的典範轉移。',
      theory: '1750 億參數的分散式訓練架構、稀疏注意力應用與 Context Window 限制。',
      flood: '催生 Prompt Engineering 職業，也暴露出「幻覺」與「不聽指令」等基礎模型的天然缺陷。',
    },
  },
  {
    id: 'training-compute-optimal-large-language-models',
    vol: '07',
    year: 2022,
    date: '2022.03',
    title: 'Training Compute-Optimal Large Language Models',
    chineseTitle: 'Chinchilla：算力邊界的重大修訂',
    authors: 'Jordan Hoffmann, Sebastian Borgeaud, Arthur Mensch, Elena Buchatskaya et al.',
    org: 'DeepMind',
    venue: 'NeurIPS 2022',
    arxivId: '2203.15556',
    url: '/papers/training-compute-optimal-large-language-models',
    status: 'outline',
    track: 'language',
    theme: '算力最優解',
    kicker: 'VOL. 07 / COMPUTE-OPTIMAL',
    why: '業界盲目追逐數千億超大參數，但既有模型真的在給定算力下獲得最佳訓練了嗎？',
    how: '重新評估超過 400 個模型的訓練損失曲線，指出 Kaplan 原定律低估了數據的重要性；提出模型參數與訓練 token 數應以 1:1 的等比例增長。',
    what: '僅 70B 參數但訓練 1.4 兆 token 的 Chinchilla 全面擊敗 175B 的 GPT-3，扭轉了大模型研發方向：小模型配海量數據才是最高性價比。',
    outline: {
      history: 'Kaplan 定律的盲點：模型「嚴重吃不飽數據」被誤以為需要更多參數。',
      theory: '三種算力最優預算推導方法、數據與參數的等比擴增前沿。',
      flood: '啟發了 LLaMA 等一系列現代高效輕量級基座模型，改變了推論成本的經濟學。',
    },
  },
  {
    id: 'training-language-models-to-follow-instructions-with-human-feedback',
    vol: '08',
    year: 2022,
    date: '2022.03',
    title: 'Training language models to follow instructions with human feedback',
    chineseTitle: 'InstructGPT：讓人性引導機器——RLHF 對齊革命',
    authors: 'Long Ouyang, Jeffrey Wu, Xu Jiang, Diogo Almeida, Carroll Wainwright et al.',
    org: 'OpenAI',
    venue: 'NeurIPS 2022',
    arxivId: '2203.02155',
    url: '/papers/training-language-models-to-follow-instructions-with-human-feedback',
    status: 'outline',
    track: 'language',
    theme: '指令對齊',
    kicker: 'VOL. 08 / ALIGNMENT & RLHF',
    why: '單純預測下一個字的基礎模型只會接話，充斥胡言亂語、不實資訊甚至惡意偏見，根本無法作為可靠的助手。',
    how: '提出三步對齊流程：優質人類範例微調（SFT）$\to$ 人類偏好排序訓練獎勵模型（RM）$\to$ 近端策略最佳化（PPO）強化學習。',
    what: '僅 1.3B 的對齊模型在滿意度上擊敗 175B 的未對齊 GPT-3；確立 Helpful, Honest, Harmless（3H）標準，為 ChatGPT 的誕生奠定關鍵技術底座。',
    outline: {
      history: 'Alignment Problem（對齊問題）：為什麼目標函數和人類意圖會產生根本脫節？',
      theory: 'SFT、Reward Model、PPO 強化學習演算法與 KL 散度懲罰機制。',
      flood: 'AI 產品形態的決定性轉折點，ChatGPT 隨之點燃全球 AI 革命。',
    },
  },
  {
    id: 'llama-open-and-efficient-foundation-language-models',
    vol: '09',
    year: 2023,
    date: '2023.02',
    title: 'LLaMA: Open and Efficient Foundation Language Models',
    chineseTitle: 'LLaMA：開源生態大爆炸的引線',
    authors: 'Hugo Touvron, Thibaut Lavril, Gautier Izacard, Xavier Martinet et al.',
    org: 'Meta AI',
    venue: 'arXiv Preprint',
    arxivId: '2302.13971',
    url: '/papers/llama-open-and-efficient-foundation-language-models',
    status: 'outline',
    track: 'language',
    theme: '開源民主化',
    kicker: 'VOL. 09 / OPEN FOUNDATION',
    why: '最強大的前沿模型被封閉在科技巨頭的雲端 API 後，全球學術界與開源社群無法審計、無法魔改、更無法本機部署。',
    how: '貫徹 Chinchilla 理念，僅使用完全公開透明的 1.4 兆 token 訓練 7B 至 65B 參數的高效能模型，並向學術界開放權重。',
    what: '引爆全球開源 LLM 的繁榮浪潮（Alpaca, Vicuna, LoRA, llama.cpp），打破閉源壟斷，讓千家萬戶的個人電腦也能運行大模型。',
    outline: {
      history: '開源與閉源的世紀大分水嶺：如何用平民級算力打破巨頭封鎖？',
      theory: 'RMSNorm、SwiGLU 激活函數、Rotary Position Embedding (RoPE) 等現代架構工程最佳實踐。',
      flood: '推動邊緣運算、量化微調技術（QLoRA），開源生態與閉源巨頭形成雙雄抗衡。',
    },
  },
  {
    id: 'direct-preference-optimization-your-language-model-is-secretly-a-reward-model',
    vol: '10',
    year: 2023,
    date: '2023.05',
    title: 'Direct Preference Optimization: Your Language Model is Secretly a Reward Model',
    chineseTitle: 'DPO：告別繁瑣強化學習的直接偏好優化',
    authors:
      'Rafael Rafailov, Archit Sharma, Eric Mitchell, Stefano Ermon, Christopher D. Manning, Chelsea Finn',
    org: 'Stanford University',
    venue: 'NeurIPS 2023',
    arxivId: '2305.18290',
    url: '/papers/direct-preference-optimization-your-language-model-is-secretly-a-reward-model',
    status: 'outline',
    track: 'language',
    theme: '偏好優化',
    kicker: 'VOL. 10 / DIRECT PREFERENCE',
    why: 'RLHF 中的 PPO 演算法極難訓練，容易發生獎勵崩潰（Reward Hacking），且需要維護多個模型，算力負擔沉重。',
    how: '從數學上推導出「語言模型本身就是其自身隱含的獎勵函數」，省去顯式獎勵模型，直接用一個簡單的二元交叉熵損失函數在偏好數據對上進行訓練。',
    what: '訓練極其穩定且計算成本劇降，迅速被開源社群（如 Zephyr, Llama-3 微調）普遍採納，成為現代模型對齊不可或缺的標準基石。',
    outline: {
      history: 'RLHF 的工程痛點：PPO 的高敏感度超參數與難以穩定的訓練循環。',
      theory: 'Bradley-Terry 偏好模型推導、解析解代入策略損失函數的精妙數學推論。',
      flood: '推動 Alignment 普及化，促成 IPO、KTO、ORPO 等後續直接偏好對齊演算法的蓬勃發展。',
    },
  },

  // ==================== 系列二：視覺與原生多模態革命 ====================
  {
    id: 'an-image-is-worth-16x16-words-transformers-for-image-recognition-at-scale',
    vol: '11',
    year: 2020,
    date: '2020.10',
    title: 'An Image is Worth 16x16 Words: Transformers for Image Recognition at Scale',
    chineseTitle: 'ViT：一張圖片等於 16x16 個單字——視覺大一統',
    authors: 'Alexey Dosovitskiy, Lucas Beyer, Alexander Kolesnikov, Dirk Weissenborn et al.',
    org: 'Google Research, Brain Team',
    venue: 'ICLR 2021',
    arxivId: '2010.11929',
    url: '/papers/an-image-is-worth-16x16-words-transformers-for-image-recognition-at-scale',
    status: 'outline',
    track: 'multimodal',
    theme: '視覺統一',
    kicker: 'VOL. 11 / VISION TRANSFORMER',
    why: '過去三十年電腦視覺被 CNN 壟斷；直接把百萬像素送進 Transformer 會讓 Self-Attention 的 $N \times N$ 分數表直接膨脹到上兆，記憶體瞬間炸開。',
    how: '將整張圖片切成 $16 \times 16$ 像素的小圖塊（Patch），拉平成向量當作「視覺單字」，直接送入標準純粹的 Transformer Encoder。',
    what: '證明純 Transformer 在充足大數據下能全面擊敗 CNN，打破了 CV 與 NLP 的學科壁壘，為現代多模態鋪平道路。',
    outline: {
      history: 'CNN 歸納偏置（Inductive Bias）的優勢與束縛：局部卷積核為什麼看不到全域長距離依賴？',
      theory:
        'Patch Embedding 投影矩陣、類別標籤 Token [CLS] 與二維位置編碼（Positional Embedding）。',
      flood:
        '啟發 Swin Transformer、MAE（Masked Autoencoders），成為多模態模型「眼睛」的共同標準。',
    },
    draftSections: [
      {
        heading: '為什麼不能直接把「每個像素」當作 Token？',
        body: '文字序列通常幾百到幾千個單字，Self-Attention 運算量是長度的平方 $O(N^2)$。但一張看似普通的 $1024 \times 1024$ 照片，就包含超過 100 萬顆像素！如果一顆像素算一個 Token，注意力分數矩陣將高達 $10^{12}$（一兆筆運算），任何超級電腦的顯示記憶體都會在瞬間癱瘓。ViT 的絕妙之處在於「把圖片當拼圖」：切成 $16 \times 16$ 的小 Patch 後，100 萬像素被壓縮成僅僅 4096 個小方塊，終於能被 Transformer 輕鬆運算。',
      },
      {
        heading: '打破 CNN 壟斷：語言與視覺第一次說同一種母語',
        body: '在 ViT 出現前，所有人都認為圖像有二維空間局部性，必須用 CNN 的滑動卷積核來處理。ViT 用最激進的方式證明：只要預訓練資料夠大，標準 Transformer 不需要任何針對二維影像特化的卷積結構，就能自己學會邊緣、紋理、光影與語意。從此，電腦視覺與自然語言處理，底層演算法全部歸流於 Attention。',
      },
    ],
  },
  {
    id: 'learning-transferable-visual-models-from-natural-language-supervision',
    vol: '12',
    year: 2021,
    date: '2021.02',
    title: 'Learning Transferable Visual Models From Natural Language Supervision',
    chineseTitle: 'CLIP：文字與影像共享同一套世界座標',
    authors: 'Alec Radford, Jong Wook Kim, Chris Hallacy, Aditya Ramesh, Gabriel Goh et al.',
    org: 'OpenAI',
    venue: 'ICML 2021',
    arxivId: '2103.00020',
    url: '/papers/learning-transferable-visual-models-from-natural-language-supervision',
    status: 'outline',
    track: 'multimodal',
    theme: '多模態對齊',
    kicker: 'VOL. 12 / CONTRASTIVE ALIGNMENT',
    why: '傳統影像分類器是封閉集合（例如只能認 ImageNet 的 1000 種固定類別），完全無法理解人類豐富多樣的開放語言描述。',
    how: '爬取網路 4 億對圖文數據，設計雙塔架構（Text Encoder + Image Encoder），以對比學習（Contrastive Learning）把文字與圖片特徵拉到同一個高維向量空間中彼此對齊。',
    what: '讓模型能直接以自然語言進行零樣本分類（Zero-shot Classification）；成為所有後續文字生圖（DALL-E 2/3、Stable Diffusion）的核心文字引導大腦。',
    outline: {
      history: '傳統分類器的語意孤島：為什麼電腦認得「狗」，卻不認得「一隻戴著草帽在衝浪的柴犬」？',
      theory: '對比學習矩陣、餘弦相似度最大化、對角線正樣本與非對角線負樣本的 InfoNCE 損失推導。',
      flood: '奠定文字到影像跨模態生成的語意座標系統，多模態檢索與生圖時代正式到來。',
    },
    draftSections: [
      {
        heading: '為什麼文字與圖片需要「對齊到同一個空間」？',
        body: '想像一個只會說中文的文字模型，和一個只會看圖形的視覺模型。如果文字模型說「黃金獵犬在雪地奔跑」，視覺模型根本聽不懂這串字對應哪些顏色和線條。CLIP 就像一位宇宙翻譯官：它拿四億張圖片和其對應的圖說，在數學的高維空間裡建立了一張統一座標地圖。在這張地圖上，「黃金獵犬文字向量」和「真正的獵犬照片特徵」被狠狠拉到同一個點上，從此讓電腦真正看懂了文字指令與畫面的對應關係。',
      },
    ],
  },
  {
    id: 'high-resolution-image-synthesis-with-latent-diffusion-models',
    vol: '13',
    year: 2022,
    date: '2021.12',
    title: 'High-Resolution Image Synthesis with Latent Diffusion Models',
    chineseTitle: '潛在擴散模型 (Stable Diffusion)：從混沌噪點中雕刻圖像',
    authors: 'Robin Rombach, Andreas Blattmann, Dominik Lorenz, Patrick Esser, Björn Ommer',
    org: 'LMU Munich / Runway / Stability AI',
    venue: 'CVPR 2022 (Oral)',
    arxivId: '2112.10752',
    url: '/papers/high-resolution-image-synthesis-with-latent-diffusion-models',
    status: 'outline',
    track: 'multimodal',
    theme: '擴散生成',
    kicker: 'VOL. 13 / LATENT DIFFUSION',
    why: '在像素空間直接做擴散去噪（DDPM）算力成本極其高昂，高解析度生成需要百張 GPU 訓練數月，一般研究者與個人顯卡根本無法運行。',
    how: '先用自編碼器（VAE）將圖片壓縮成空間尺寸小 8 倍的「隱空間（Latent Space）」，在隱空間進行反向去噪，並透過 Cross-Attention 接入 CLIP 文字引導。',
    what: '催生了開源現象級應用 Stable Diffusion 與 Midjourney；確立 2022–2024 擴散生圖統治地位，但也留下了「牽一髮動全身」難以精確局部修改的困境。',
    outline: {
      history: 'GAN 的崩潰模式 vs. 擴散模型的穩定去噪：為什麼物理熱力學逆過程能畫圖？',
      theory: '前向加噪馬可夫鏈、反向神經網路去噪、VAE 感知壓縮與 Cross-Attention 條件注入機制。',
      flood:
        '引爆個人電腦本機生圖浪潮（WebUI, ControlNet），但也暴露出文字拼寫錯誤與隨機性漂移的盲點。',
    },
    draftSections: [
      {
        heading: '核心討論：為什麼「噪點生成」就像畫家打草稿？',
        body: '人類畫畫從來不是像印表機一樣從左上角一行行印到右下角，而是「大勢構圖 $\to$ 肢體輪廓 $\to$ 高光細節」。擴散模型（Diffusion）在數學上去噪的過程，恰好重演了這個畫家心智：在最初的高噪點階段，畫面宛如電視雪花，模型首先捕捉的是低頻大佈局（上方是藍天大色塊、下方是綠地）；在中度去噪階段，粗糙的輪廓與造型被確定下來；在最後的微噪點階段，模型才負責把毛孔、髮絲走向、反光等高頻細節刻畫完畢。',
      },
      {
        heading: '致命痛點：為什麼傳統擴散模型「修改圖片極其痛苦」？',
        body: '在擴散模型中，整張圖是由一整塊連續隨機噪點洗出來的。如果你好不容易生成了一張完美的少女畫像，只想要「幫她戴上一副眼鏡」，只要在 Prompt 裡加了「眼鏡」，去噪軌跡就會發生全域混沌漂移——重新跑一次，連少女的長相、髮型、背景甚至光影全部換了一個人！即使使用手動筆刷塗黑遮罩的 Inpainting（局部重繪），接縫處也極易出現光影斷裂與色差，難以實現多輪對話式的連續微調。',
      },
      {
        heading: '文字渲染的鬼畫符之謎',
        body: '為什麼早期的 Midjourney 或 Stable Diffusion 畫海報或商店招牌時，上面的英文總是變成莫名其妙的火星文？因為擴散模型是視覺統計模型，它「看過很多招牌長那樣」，但它大腦裡沒有離散字符的語義拼寫大腦。它在模擬文字的「視覺質感」，而不是在「寫出單字」。這為後續轉向自回歸架構埋下了最深的伏筆。',
      },
    ],
  },
  {
    id: 'visual-instruction-tuning',
    vol: '14',
    year: 2023,
    date: '2023.04',
    title: 'Visual Instruction Tuning',
    chineseTitle: 'LLaVA：讓語言模型長出眼睛的視覺指令微調',
    authors: 'Haotian Liu, Chunyuan Li, Qingyang Wu, Yong Jae Lee',
    org: 'University of Wisconsin-Madison / Microsoft Research',
    venue: 'NeurIPS 2023 (Oral)',
    arxivId: '2304.08485',
    url: '/papers/visual-instruction-tuning',
    status: 'outline',
    track: 'multimodal',
    theme: '視覺問答',
    kicker: 'VOL. 14 / VISUAL INSTRUCTION TUNING',
    why: '視覺模型（ViT）只能吐出特徵向量，語言大腦（LLaMA）只看得懂文字 Token；如何用最低成本讓成熟的語言模型學會「看圖說話」與複雜多輪推理？',
    how: '以一個簡單的線性投影層（Projection Layer）將 CLIP ViT 的視覺 Token 映射到語言模型的輸入維度，並利用 GPT-4 構建高品質多模態對話數據進行端到端微調。',
    what: '確立了現代開源多模態視覺語言模型（VLM）的標準基石；證明了不需要從頭訓練兆級多模態大模型，極簡外掛即可賦予語言模型強大的圖像理解力。',
    outline: {
      history: '多模態拼裝車的困境：傳統跨模態架構過度複雜，如何輕量化打通語言大腦與視覺神經？',
      theory:
        '視覺特徵線性對齊、兩階段訓練（特徵對齊預訓練 $\to$ 視覺指令微調）、多模態對話資料構造法。',
      flood:
        '催生 LLaVA-1.5、Qwen-VL 等繁榮開源生態，但外掛式結構依舊只能「看圖答題」，無法在同一大腦裡「自由改圖」。',
    },
    draftSections: [
      {
        heading: '極簡設計的勝利：一條線性轉譯層的大智慧',
        body: 'LLaVA 的架構簡潔得令人難以置信：它保留現成最強的視覺模型（CLIP ViT）當眼睛，保留現成最強的文字模型（LLaMA）當大腦，中間只用了一個最簡單的投影矩陣 $W$！這層矩陣的作用就像一副轉譯眼鏡，把視網膜傳來的像素特徵向量，換算成語言大腦熟悉的 Word Embedding格式。這證明了大語言模型本身的通用語意空間足夠強大，只要輸入格式被對齊，它就能自然而然地對著圖像進行邏輯推理。',
      },
    ],
  },
  {
    id: 'visual-autoregressive-modeling-scalable-image-generation-via-next-scale-prediction',
    vol: '15',
    year: 2024,
    date: '2024.04',
    title: 'Visual AutoRegressive Modeling: Scalable Image Generation via Next-Scale Prediction',
    chineseTitle: 'VAR 與原生視覺自回歸：像編輯 Word 一樣精準修圖',
    authors: 'Keyu Tian, Yi Jiang, Zehuan Yuan, Bingyue Peng, Liwei Wang',
    org: 'ByteDance / Peking University',
    venue: 'NeurIPS 2024 (Best Paper)',
    arxivId: '2404.02905',
    url: '/papers/visual-autoregressive-modeling-scalable-image-generation-via-next-scale-prediction',
    status: 'outline',
    track: 'multimodal',
    theme: '原生自回歸生圖',
    kicker: 'VOL. 15 / NEXT-SCALE AUTOREGRESSION',
    why: '傳統擴散模型每次改圖都在全域重新隨機抽卡，無法局部精確微調；而傳統自回歸生圖（如 Image-GPT）像印表機一樣從左上掃到右下，缺乏全域宏觀視野。',
    how: '提出「下一尺度預測（Next-Scale Prediction）」範式：打破平鋪光柵掃描，以多尺度視覺碼本自回歸地從 $1 \times 1$ 粗略構圖到 $64 \times 64$ 細膩紋理逐級生成；並與 GPT-4o 原生多模態 Token 理念共振。',
    what: '自回歸生圖在畫質、速度與縮放定律上首度擊敗擴散變壓器（DiT）；為「文字、影像同源自回歸」與「多輪對話精準局部編輯」奠定新一代黃金標準。',
    outline: {
      history: '從光柵掃描（Raster-scan）到多尺度草圖（Next-Scale）：視覺到底應該如何自回歸？',
      theory: '多尺度離散量化編碼器（Multi-Scale VQ-VAE）、跨尺度自回歸注意力遮罩與縮放定律驗證。',
      flood:
        '推動 OpenAI GPT Image 與多模態原生自回歸大一統，實現「指哪改哪、像改文件一樣改圖」的終極願景。',
    },
    draftSections: [
      {
        heading: '核心解答：自回歸為什麼能做到「指哪改哪，不重畫整張圖」？',
        body: '在原生多模態自回歸模型（如 GPT-4o 的 GPT Image）眼中，圖片是一串排好座位的「視覺 Token」。當你說「把貓的眼睛改成藍色」時，原圖的 Token 序列就原封不動躺在上下文視窗（Context Window）裡。Self-Attention 告訴模型：背景、草地、貓的毛色完全沒有被指令提及，直接照抄原圖的 Token；只有讀到眼睛所在的特定 Token 位置時，模型調用語言推理大腦，只針對那幾個 Token 重新預測新值！這就是為什麼它能做到真正的多輪對話一致性，不用再拿筆刷塗遮罩，更不會整張圖變形換人。',
      },
      {
        heading: '突破印表機思維：Next-Scale 讓自回歸也學會「畫草圖」',
        body: '過去業界排斥自回歸生圖的一大原因，是以前的做法像打字機一樣，從第 1 顆像素從左到右、從上到下印到最後一顆。人類畫畫絕不是印表機！VAR（NeurIPS 2024 最佳論文）震撼學界的地方，在於它把自回歸的「下一步預測」改成了「下一尺度預測」：第一步先預測一張超低解析度的全局模糊大色塊（粗草稿），第二步在此基礎上預測中度結構，第三步、第四步逐步預測出精緻毛孔與紋理。它完美結合了「擴散模型的畫家草圖美學」與「Transformer 自回歸的強大邏輯控制力」！',
      },
    ],
  },
];
